### ISSUE TITLE
vcf_to_SIFT4g

### ISSUE THREAD

**Issue by BaHole** [evodify/genotype-files-manipulations#1]
ModuleNotFoundError: No module named 'calls'

**Comment by evodify** [comment]
You need to download [calls.py](https://github.com/evodify/genotype-files-manipulations/blob/master/calls.py) and place it in the same directory with [vcf_to_SIFT4G.py](https://github.com/evodify/genotype-files-manipulations/blob/master/vcf_to_SIFT4G.py)
